// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfddtbrvvvvejhwgebnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmZGR0YnJ2dnZ2ZWpod2dlYm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Mjc4MDIsImV4cCI6MjA2MjIwMzgwMn0.InH368RBfHYpNGTPsiQRH5p_p1E4vPbVsp2ICiSlc6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);